from ctypes import*
def t(c,*_):c.restype=c_void_p;c.argtypes=[c_void_p]*len(_);return c(*_)
u=CDLL("libc.so.6")
c=CDLL("libclutter-1.0.so.0")
l=CDLL("libgobject-2.0.so.0")
t(c.clutter_init,0)
e=t(c.clutter_stage_new)
_=t(c.clutter_shader_effect_new,1)
t(c.clutter_shader_effect_set_shader_source,_,b"void main(){cogl_color_out=vec4(cogl_tex_coord_in[0].xxy,1.);}")
t(c.clutter_actor_add_effect,e,_)
t(l.g_signal_connect_data,e,b"delete-event",c.clutter_main_quit,0,0,0)
t(u.signal,2,c.clutter_main_quit)
t(c.clutter_actor_show,e)
t(c.clutter_main)
